DROP TABLE IF EXISTS inventory_contents CASCADE;
DROP TABLE IF EXISTS known_recipes CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS root_nodes CASCADE;
DROP TABLE IF EXISTS nodes CASCADE;
DROP TABLE IF EXISTS spells CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS properties CASCADE;

DROP FUNCTION utc_now();